services:
  mongodb:
    image: mongo:8.0
    container_name: formpf3-mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB}
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
      - ./logs:/var/log/mongodb
      - ./init:/docker-entrypoint-initdb.d:ro
    networks:
      - mongo-net

networks:
  mongo-net:
    driver: bridge
